#!/bin/bash
docker build . -t docker-pipeline --build-arg TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY} --build-arg TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET} --build-arg TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN} --build-arg TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
